import java.util.ArrayList;

/**
 * Created by MichaelApposing on 01/12/2016.
 */
public class PEmain2 {

    public static void main(String[] args) {
        //Problem 2
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


        ArrayList<Integer> fibonacci = new ArrayList<>();
        fibonacci.add(1);
        fibonacci.add(2);

        while (fibonacci.get(fibonacci.size() - 1) < 4000000) {
            fibonacci.add(getNextNum(fibonacci.get(fibonacci.size() - 1), fibonacci.get(fibonacci.size() - 2)));
        }

        int total = 0;

        for (int i = 0; i < fibonacci.size(); i++) {

            if (fibonacci.get(i) % 2 == 0) {
                total += fibonacci.get(i);
            }
        }
        Util.printOut("Problem 2", total);
    }


    private static int getNextNum(int num1, int num2) {
        return num1 + num2;
    }
}
